name: brilliantlens
favicon: null
layout_spectrum: 0.830924001056701
typography_spectrum: 0.7321133478544652
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.3757311685476452
  lightness: 0.15501599432900548
  saturation: 0.5368930385448039
  rhythmicContrast: 0.61194864846766
purpose: []
